data_case: duffing
train_dataset: ../data/case1b_train.npy
test_dataset: ../data/case1_test.npy
save_in: ../weights/case1b/
model_type: ParametricDeepONet
input_dim: 200
params_dim: 2
loss_mode: NRMSE
optimizer: Adam
params_normalize: False 
params_label: ['k', 'c']
run: 1 
epoch: 10000 
seed: None
print_every: 1000
batch_size: 64 
lr: 0.001
decode_mode: nonlinear
depth: 3
width: 300
pebasis: 10
